### ISSUE TITLE
Charging Station > Reboot Charging Station popup 

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1658]
After you are changing a plan/Static Limitation/Temporary planning a popup appears asking if you when to restart the Charging Station.

This popup is irrelevant and may stop an ongoing charging session

**Comment by LucasBrazi06** [comment]
@fcoutellier , the charging station returns us the **RebootRequired** message when we change an OCPP parameter, this is why the pop-up is shown otherwise the parameter is not taken into account (except for Cahors). If the param change does not require reboot we receive the **Accepted** message and in that case the reboot pop-up is not shown.
