### ISSUE TITLE
Hide Static limitation Tab when Smart Charging is enabled.

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1854]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/ec9a6568-6c81-469b-8ca2-9dc7dbb3d801)

**Comment by jerome-benoit** [comment]
We have to make sure that the OCPP parameter used for the static limitation has been properly reset to its maximum value before enabling smart charging.

**Comment by fcoutellier** [comment]
Correct, but it seems to be the case already. I haven't notice any issue on this yet.

**Comment by jerome-benoit** [comment]
> Correct, but it seems to be the case already. I haven't notice any issue on this yet.

I have to check in the code but to be sure: 

+ Put a station in a zone without smart charging; 
+ Play with the static limitation; 
+ Enable smart charging in the zone;
+ Check that the static limitation has been properly reset to the maximum. 

So if you hide completely that tab or its content, that kind of check cannot be done from the dashboard. We can find something in-between that still permit to do it.

**Comment by LucasBrazi06** [comment]
The static limitation should not be reset.

**Comment by jerome-benoit** [comment]
> The static limitation should not be reset.

Which settings win on the charging station (the value in the DB should not be reset)? charging profiles or current limitation OCPP parameter?

Currently, we can't have that scenario: I want to use smart charging algorithm within an already defined static limitation limit because it duplicates the per zone smart charging power limitation feature. 
But we have to make sure that on all charging stations firmware that have use static limitation before smart charging enablement, the charging profile settings always take over the current limitation setting via OCPP param. If we are not sure, we have to reset the current limitation value to the maximum before smart charging enablement on a charging station, and but back the value used after smart charging disablement.

**Comment by LucasBrazi06** [comment]
Charging plan wins over the OCPP param.

**Comment by LucasBrazi06** [comment]
Let the static limitation displayed with an explanation in the end as it'll be weird for the user to not see it anymore!
