### ISSUE TITLE
Sessions > Filter: Add Connector ID filter

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2189]

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane is there backend impl also?

**Comment by WillyLellouch** [comment]
Is there a particular use case for this ? Are the Connectors Ids necessarily a capital letter in the A-Z range ?

**Comment by mahdibenromdhane** [comment]
> Is there a particular use case for this ? Are the Connectors Ids necessarily a capital letter in the A-Z range ?

No particular use case, It's a connector filter in A-Z capital letter.

**Comment by LucasBrazi06** [comment]
> Is there a particular use case for this ? Are the Connectors Ids necessarily a capital letter in the A-Z range ?

One of our customer wants to export only sessions for a given connector.

**Comment by WillyLellouch** [comment]
> One of our customer wants to export only sessions for a given connector.
OK the functionality works well, I have just 2 remarks before closing the issue :
- The Connector ID that is exported is the backend's so it's a numerical value rather than the "translated" A-Z letter. I noticed that in the csv files I got. I'm not sure it's an issue however I thought I'd take note of it anyway.
- The design of the functionality is simple and accessible, however I think there could be a way to integrate future use cases (i.e. choosing different connectors for multiple stations). However this doesn't fall into the current use case cited above and could be left for if/when there is an actual need.

**Comment by LucasBrazi06** [comment]
> * The Connector ID that is exported is the backend's so it's a numerical value rather than the "translated" A-Z letter. I noticed that in the csv files I got. I'm not sure it's an issue however I thought I'd take note of it anyway.

Connector ID on REST endpoint is numerical which is fine I think.

> * The design of the functionality is simple and accessible, however I think there could be a way to integrate future use cases (i.e. choosing different connectors for multiple stations). However this doesn't fall into the current use case cited above and could be left for if/when there is an actual need.

Yes why not but not in the context of that issue.

**Comment by WillyLellouch** [comment]
Then I'll close the issue.
